mode = "debug"
name = "go-tasks"
host = "http://127.0.0.1:8086"
grpc-port = 50050
http-port = 8086

jwt-secret-key = "4ab079c4640826102a03656350f21477"


[db]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456"
db-name = "go_tasks"
#最大空闲连接数
max-idle-connections = 1
#最大打开的连接数
max-open-connections = 1





