// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: grpc/master.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Master_NodeRegister_FullMethodName  = "/service.Master/NodeRegister"
	Master_TaskExecRes_FullMethodName   = "/service.Master/TaskExecRes"
	Master_ProcessNotice_FullMethodName = "/service.Master/ProcessNotice"
)

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterClient interface {
	NodeRegister(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
	TaskExecRes(ctx context.Context, in *TaskExecResRequest, opts ...grpc.CallOption) (*TaskExecResResponse, error)
	ProcessNotice(ctx context.Context, in *ProcessNoticeRequest, opts ...grpc.CallOption) (*ProcessNoticeResponse, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) NodeRegister(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, Master_NodeRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) TaskExecRes(ctx context.Context, in *TaskExecResRequest, opts ...grpc.CallOption) (*TaskExecResResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExecResResponse)
	err := c.cc.Invoke(ctx, Master_TaskExecRes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) ProcessNotice(ctx context.Context, in *ProcessNoticeRequest, opts ...grpc.CallOption) (*ProcessNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessNoticeResponse)
	err := c.cc.Invoke(ctx, Master_ProcessNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
// All implementations must embed UnimplementedMasterServer
// for forward compatibility.
type MasterServer interface {
	NodeRegister(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	TaskExecRes(context.Context, *TaskExecResRequest) (*TaskExecResResponse, error)
	ProcessNotice(context.Context, *ProcessNoticeRequest) (*ProcessNoticeResponse, error)
	mustEmbedUnimplementedMasterServer()
}

// UnimplementedMasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServer struct{}

func (UnimplementedMasterServer) NodeRegister(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeRegister not implemented")
}
func (UnimplementedMasterServer) TaskExecRes(context.Context, *TaskExecResRequest) (*TaskExecResResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskExecRes not implemented")
}
func (UnimplementedMasterServer) ProcessNotice(context.Context, *ProcessNoticeRequest) (*ProcessNoticeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessNotice not implemented")
}
func (UnimplementedMasterServer) mustEmbedUnimplementedMasterServer() {}
func (UnimplementedMasterServer) testEmbeddedByValue()                {}

// UnsafeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServer will
// result in compilation errors.
type UnsafeMasterServer interface {
	mustEmbedUnimplementedMasterServer()
}

func RegisterMasterServer(s grpc.ServiceRegistrar, srv MasterServer) {
	// If the following call pancis, it indicates UnimplementedMasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Master_ServiceDesc, srv)
}

func _Master_NodeRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).NodeRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Master_NodeRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).NodeRegister(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_TaskExecRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecResRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).TaskExecRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Master_TaskExecRes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).TaskExecRes(ctx, req.(*TaskExecResRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_ProcessNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).ProcessNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Master_ProcessNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).ProcessNotice(ctx, req.(*ProcessNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Master_ServiceDesc is the grpc.ServiceDesc for Master service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Master_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeRegister",
			Handler:    _Master_NodeRegister_Handler,
		},
		{
			MethodName: "TaskExecRes",
			Handler:    _Master_TaskExecRes_Handler,
		},
		{
			MethodName: "ProcessNotice",
			Handler:    _Master_ProcessNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/master.proto",
}
