// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: grpc/master.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type TaskExecResRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     int64  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	LogId      int64  `protobuf:"varint,2,opt,name=logId,proto3" json:"logId,omitempty"`
	TaskStatus int64  `protobuf:"varint,3,opt,name=taskStatus,proto3" json:"taskStatus,omitempty"` // 0：等待执行， 1：执行完成， -1： 错误信息
	Message    string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TaskExecResRequest) Reset() {
	*x = TaskExecResRequest{}
	mi := &file_grpc_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecResRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecResRequest) ProtoMessage() {}

func (x *TaskExecResRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecResRequest.ProtoReflect.Descriptor instead.
func (*TaskExecResRequest) Descriptor() ([]byte, []int) {
	return file_grpc_master_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecResRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskExecResRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *TaskExecResRequest) GetTaskStatus() int64 {
	if x != nil {
		return x.TaskStatus
	}
	return 0
}

func (x *TaskExecResRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 响应消息
type TaskExecResResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TaskExecResResponse) Reset() {
	*x = TaskExecResResponse{}
	mi := &file_grpc_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecResResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecResResponse) ProtoMessage() {}

func (x *TaskExecResResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecResResponse.ProtoReflect.Descriptor instead.
func (*TaskExecResResponse) Descriptor() ([]byte, []int) {
	return file_grpc_master_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecResResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TaskExecResResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 请求消息
type ProcessNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId int64  `protobuf:"varint,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProcessNoticeRequest) Reset() {
	*x = ProcessNoticeRequest{}
	mi := &file_grpc_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNoticeRequest) ProtoMessage() {}

func (x *ProcessNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNoticeRequest.ProtoReflect.Descriptor instead.
func (*ProcessNoticeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_master_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessNoticeRequest) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ProcessNoticeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 响应消息
type ProcessNoticeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProcessNoticeResponse) Reset() {
	*x = ProcessNoticeResponse{}
	mi := &file_grpc_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNoticeResponse) ProtoMessage() {}

func (x *ProcessNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNoticeResponse.ProtoReflect.Descriptor instead.
func (*ProcessNoticeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_master_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessNoticeResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProcessNoticeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 请求消息
type NodeRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *NodeRegisterRequest) Reset() {
	*x = NodeRegisterRequest{}
	mi := &file_grpc_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterRequest) ProtoMessage() {}

func (x *NodeRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterRequest.ProtoReflect.Descriptor instead.
func (*NodeRegisterRequest) Descriptor() ([]byte, []int) {
	return file_grpc_master_proto_rawDescGZIP(), []int{4}
}

func (x *NodeRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeRegisterRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// 响应消息
type NodeRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NodeRegisterResponse) Reset() {
	*x = NodeRegisterResponse{}
	mi := &file_grpc_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterResponse) ProtoMessage() {}

func (x *NodeRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterResponse.ProtoReflect.Descriptor instead.
func (*NodeRegisterResponse) Descriptor() ([]byte, []int) {
	return file_grpc_master_proto_rawDescGZIP(), []int{5}
}

func (x *NodeRegisterResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NodeRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_master_proto protoreflect.FileDescriptor

var file_grpc_master_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x7c, 0x0a, 0x12,
	0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x54, 0x61,
	0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x4e, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x45, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x14, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xef, 0x01, 0x0a, 0x06,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x52,
	0x65, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78,
	0x65, 0x63, 0x52, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x1d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a,
	0x16, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_master_proto_rawDescOnce sync.Once
	file_grpc_master_proto_rawDescData = file_grpc_master_proto_rawDesc
)

func file_grpc_master_proto_rawDescGZIP() []byte {
	file_grpc_master_proto_rawDescOnce.Do(func() {
		file_grpc_master_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_master_proto_rawDescData)
	})
	return file_grpc_master_proto_rawDescData
}

var file_grpc_master_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_master_proto_goTypes = []any{
	(*TaskExecResRequest)(nil),    // 0: service.TaskExecResRequest
	(*TaskExecResResponse)(nil),   // 1: service.TaskExecResResponse
	(*ProcessNoticeRequest)(nil),  // 2: service.ProcessNoticeRequest
	(*ProcessNoticeResponse)(nil), // 3: service.ProcessNoticeResponse
	(*NodeRegisterRequest)(nil),   // 4: service.NodeRegisterRequest
	(*NodeRegisterResponse)(nil),  // 5: service.NodeRegisterResponse
}
var file_grpc_master_proto_depIdxs = []int32{
	4, // 0: service.Master.NodeRegister:input_type -> service.NodeRegisterRequest
	0, // 1: service.Master.TaskExecRes:input_type -> service.TaskExecResRequest
	2, // 2: service.Master.ProcessNotice:input_type -> service.ProcessNoticeRequest
	5, // 3: service.Master.NodeRegister:output_type -> service.NodeRegisterResponse
	1, // 4: service.Master.TaskExecRes:output_type -> service.TaskExecResResponse
	3, // 5: service.Master.ProcessNotice:output_type -> service.ProcessNoticeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_master_proto_init() }
func file_grpc_master_proto_init() {
	if File_grpc_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_master_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_master_proto_goTypes,
		DependencyIndexes: file_grpc_master_proto_depIdxs,
		MessageInfos:      file_grpc_master_proto_msgTypes,
	}.Build()
	File_grpc_master_proto = out.File
	file_grpc_master_proto_rawDesc = nil
	file_grpc_master_proto_goTypes = nil
	file_grpc_master_proto_depIdxs = nil
}
